### ISSUE TITLE
Joulescope v2 with embedded logical analyser.

### ISSUE THREAD

**Issue by rsglobal** [jetperch/joulescope_front_panels#2]
Hello guys,

Thank you for this nice tool.
As a user I may want to put some labels to the graph to match power consumption to some software events.
Usual way to do this is to use some MCU output pin and connect it to the scope together with measuring signal.

In case you like this idea, consider starting another Kickstarter campaign.

Regards.

**Comment by mliberty1** [comment]
Hi @rsglobal and thank you for the feedback.

You may be able to do this today using the two general-purpose inputs located next to the host USB port.  Here is an example showing a GPIO event and a related current :
![image](https://user-images.githubusercontent.com/5393422/81474575-73cb0280-91d4-11ea-8e40-b5f6d03f6d75.png)

The two GPIOs are USB ground referenced, so you may need additional external isolators if your target system is not earth ground referenced.  

Does this do what you need?  If not, could you add more detail so that I can better understand how I could make Joulescope better for you?

**Comment by rsglobal** [comment]
Ah, that's great. I've missed those pins on the device photo and project homepage.

Thank you for your fast response.
